version: "3"
services:
  backend:
    image: renz7/sd-backend
    container_name: sd-backend
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./output/:/home/runner/output/
    depends_on:
      - init-db
      - redis
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: wav2lip
      MYSQL_ROOT_PASSWORD: 1233
  init-db:
    image: renz7/sd-backend
    env_file:
      - .env
    command:
      - initdb
    depends_on:
      - mysql
  celery:
    image: renz7/sd-backend
    container_name: celery-worker
    volumes:
      - ./output/:/runner/output/
    env_file:
      - .env
    command:
      - celery
    depends_on:
      - redis
  flower:
    image: renz7/sd-backend
    container_name: celery_flower
    env_file:
      - .env
    entrypoint:
      - celery
      - --broker=${broker}
      - flower
      - --loglevel=info
      - --url_prefix=flower
  sd-webui:
    image: renz7/sd-webui:1.0.1
    container_name: sd-webui
    env_file:
      - .env
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1
